### ISSUE TITLE
registration-free COM may be failing in unit tests on clean machine

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/binskim#127] opened 2018-01-23 21:53 UTC

**Comment by Evmaus-MS** [comment] 2018-01-24 00:42
I can provide a workaround for this from earlier today.

Clean machine, install VS2017, sync master, run tests -> tests fail with COM class missing/not registered.

Install VS2015.3 on the machine, run tests -> tests will pass.

Something about a VS2015 install fixes the issue, although I'm not sure what's the root cause.

**Comment by paddymcd-MSFT** [comment] 2018-01-24 05:09
It is because 2017 is the first VS to install side by side and so efforts were made across the entire product to remove as many uses  / dependency upon system wide registrations.

So no more registering COM servers where possible.

p

Sent from my Windows 10 phone

**Comment by michaelcfanning** [comment] 2018-01-29 20:27
so VS2015 is registering MSDIA140.dll. our tests could do this as well (and unregister too), though this would require admin elevation.

**Comment by Evmaus-MS** [comment] 2018-07-26 22:15
Now a duplicate of:  https://github.com/Microsoft/binskim/issues/173

We'll track this there.

**Closed by Evmaus-MS** 2018-07-26 22:15 UTC

**Comment by denchik778** [comment] 2018-07-27 16:34
Forkplyer_tv
